[package]
name = "tracing-subscriber"
version = "0.0.1"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

[dependencies]
tracing-core = "0.1.2"
matchers = { git = "https://github.com/hawkw/matchers.git" }
regex = "1"
lazy_static = "1"
smallvec = "0.6"
crossbeam-utils = "0.6"
indexmap = "1"

[dev-dependencies]
tracing-log = { path = "../tracing-log" }
tracing = "0.1"
